import { ethers } from "ethers";
import dotenv from "dotenv";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

dotenv.config({ path: ".env.local" });

async function main() {
  const privateKey = process.env.PRIVATE_KEY;
  if (!privateKey) throw new Error("PRIVATE_KEY not set in .env or .env.local");

  const provider = new ethers.JsonRpcProvider("https://rpc.testnet.arc.network");
  const wallet = new ethers.Wallet(privateKey, provider);

  console.log(`Deploying with account: ${wallet.address}`);
  const bal = await provider.getBalance(wallet.address);
  console.log(`Account balance: ${ethers.formatEther(bal)} USDC`);

  // Read compiled artifact (generated by hardhat compile)
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const artifactPath = join(__dirname, "..", "artifacts", "contracts", "StableFlowSplitter.sol", "StableFlowSplitter.json");
  
  const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  const { abi, bytecode } = artifact;

  if (!bytecode || bytecode === "0x") {
    throw new Error("No bytecode found in artifact. Run 'npx hardhat compile' first.");
  }

  const factory = new ethers.ContractFactory(abi, bytecode, wallet);
  console.log("Deploying StableFlowSplitter...");
  
  const contract = await factory.deploy();
  console.log("Waiting for deployment confirmation...");
  await contract.waitForDeployment();

  const deployedAddress = await contract.getAddress();
  console.log(`\n✅ StableFlowSplitter deployed to: ${deployedAddress}`);
  console.log(`\nUpdate SPLITTER_ADDRESS in src/constants/contracts.ts to: '${deployedAddress}'`);
}

main().catch((err) => {
  console.error("Deployment failed:", err.message || err);
  process.exit(1);
});
